/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// locations to search for config files that get merged into the main config
// config files can either be Java properties files or ConfigSlurper scripts

// grails.config.locations = [ "classpath:${appName}-config.properties",
//                             "classpath:${appName}-config.groovy",
//                             "file:${userHome}/.grails/${appName}-config.properties",
//                             "file:${userHome}/.grails/${appName}-config.groovy"]

// if(System.properties["${appName}.config.location"]) {
//    grails.config.locations << "file:" + System.properties["${appName}.config.location"]
// }
grails.scan.interval=10000
grails.mime.file.extensions = true // enables the parsing of file extensions from URLs into the request format
grails.mime.use.accept.header = false
grails.mime.types = [ html: ['text/html','application/xhtml+xml'],
                      xml: ['text/xml', 'application/xml'],
                      text: 'text/plain',
                      js: 'text/javascript',
                      rss: 'application/rss+xml',
                      atom: 'application/atom+xml',
                      css: 'text/css',
                      csv: 'text/csv',
                      all: '*/*',
                      json: ['application/json','text/json'],
                      form: 'application/x-www-form-urlencoded',
                      multipartForm: 'multipart/form-data'
                    ]
// The default codec used to encode data with ${}
grails.views.default.codec="none" // none, html, base64
grails.views.gsp.encoding="UTF-8"
grails.converters.encoding="UTF-8"

// enabled native2ascii conversion of i18n properties files
grails.enable.native2ascii = true

// set per-environment serverURL stem for creating absolute links
environments {
    production {
        grails.serverURL = "http://www.changeme.com"
    }
    development {
        grails.serverURL = "http://localhost:8080/${appName}"
		portal.load.defaultData=true
    }
    test {
        grails.serverURL = "http://localhost:8080/${appName}"
    }

}

// log4j configuration
log4j = {
    // Example of changing the log pattern for the default console
     appender:
  
    appenders {
		
		// file appender that writes out the URLs of the Google Chart API graphs generated by the performanceGraphAppender
		def performanceGraphFileAppender = new org.apache.log4j.FileAppender(
			fileName: "log/perfGraphs.log",
			layout: pattern(conversionPattern: '%m%n')
		)
		appender name: 'performanceGraphFileAppender', performanceGraphFileAppender
		
		// this appender creates the Google Chart API graphs
		def performanceGraphAppender = new org.perf4j.log4j.GraphingStatisticsAppender(
			graphType: 'Mean',      // possible options: Mean, Min, Max, StdDev, Count or TPS
			tagNamesToGraph: 'tag1,tag2,tag3',
			dataPointsPerGraph: 5
		)
		performanceGraphAppender.addAppender(performanceGraphFileAppender)
		appender name: 'performanceGraph', performanceGraphAppender
		
		// file appender that writes out the textual, aggregated performance stats generated by the performanceStatsAppender
		def performanceStatsFileAppender = new org.apache.log4j.FileAppender(
			fileName: "log/perfStats.log",
			layout: pattern(conversionPattern: '%m%n')  // alternatively use the StatisticsCsvLayout to generate CSV
		)
		appender name: 'performanceStatsFileAppender', performanceStatsFileAppender
		
		// this is the most important appender and first in the appender chain. it aggregates all profiling data withing a certain time frame.
		// the GraphingStatisticsAppender is attached as a child to this appender and uses its aggregated data.
		def performanceStatsAppender = new org.perf4j.log4j.AsyncCoalescingStatisticsAppender(
			timeSlice: 10000    // ms
		)

		
        console name:'stdout', layout:pattern(conversionPattern: '%c{2} %m%n')
		performanceStatsAppender.addAppender(performanceStatsFileAppender)
		performanceStatsAppender.addAppender(performanceGraphAppender)
		appender name: 'performanceStatsAppender', performanceStatsAppender
    }

    warn  'org.codehaus.groovy.grails.web.servlet',  //  controllers
	       'org.codehaus.groovy.grails.web.pages', //  GSP
	       'org.codehaus.groovy.grails.web.sitemesh', //  layouts
	       'org.codehaus.groovy.grails.web.mapping.filter', // URL mapping
	       'org.codehaus.groovy.grails.web.mapping', // URL mapping
	       'org.codehaus.groovy.grails.commons', // core / classloading
	       'org.codehaus.groovy.grails.plugins', // plugins
	       'org.codehaus.groovy.grails.orm.hibernate', // hibernate integration
	       'org.springframework',
	       'org.hibernate',
		   'com.grailsPortal'
    error 'com.grailsPortal','org.codehaus','org.springframework'
}
//constraints added 
//org.codehaus.groovy.grails.validation.ConstrainedProperty.registerNewConstraint(
//		com.grailsPortal.constraint.AddOnlyIfShiroRoleConstraint.ADD_ONLY_IF_SHIRO_ROLE_CONSTRAINT, com.grailsPortal.constraint.AddOnlyIfShiroRoleConstraint.class)
//org.codehaus.groovy.grails.validation.ConstrainedProperty.registerNewConstraint(
//		com.grailsPortal.constraint.ShiroRoleConstraint.SHIRO_ROLE_CONSTRAINT, com.grailsPortal.constraint.ShiroRoleConstraint.class)
plugins {
	h2 {
	  tcpserver { disable = false; tcpPort = 8043; tcpAllowOthers = true }
	  pgserver { disable = false; pgPort = 5432; pgAllowOthers = true; baseDir = './data/h2'; trace = '' }
	  database { //
		devdb { // a Spring DriverManagerDataSource will be created as "${databaseName}DataSource"
		  /**
		   * refer to: http://www.h2database.com/html/features.html#database_url
		   */
		  url = "jdbc:h2:mem:devDB;MODE=MYSQL"; user = "sa"; //password = ""
		  init {
			//disable = true; initClass = "org.grails.plugins.h2.DBInitializer" // create a new instance and call its init( dataSource) method
		  }
		}
	  }
	}
  }
